import {SETTLEMENT_STATUS_OBJECT} from '~/pages/calculate-management/constants'
import {ORDER_STATUS} from './common'

export enum STATUS_MENTOR_MANAGEMENT {
  PENDING = 'PENDING',
  COMPLETE = 'COMPLETE',
  CANCELED = 'CANCELED',
  ALL = 'PENDING,COMPLETE,CANCELED',
}

export enum MENTORING_TRANSACTION_STATUS {
  PENDING = 'PENDING',
  COMPLETE = 'COMPLETE',
  CANCELED = 'CANCELED',
  ALL = 'PENDING,COMPLETE,CANCELED',
}

export enum STATUS_MENTORING_FIELD {
  APPLY = 'APPLY',
  PROGRESS = 'PROGRESS',
  COMPLETE = 'COMPLETE',
  CANCEL = 'CANCEL',
}

export const SETTLEMENT_STATUS_ARRAY = [
  {
    label: '전체',
    value: 'PENDING,COMPLETE,CANCELED',
  },
  {
    label: SETTLEMENT_STATUS_OBJECT[MENTORING_TRANSACTION_STATUS.PENDING],
    value: MENTORING_TRANSACTION_STATUS.PENDING,
  },
  {
    label: SETTLEMENT_STATUS_OBJECT[MENTORING_TRANSACTION_STATUS.COMPLETE],
    value: MENTORING_TRANSACTION_STATUS.COMPLETE,
  },
  {
    label: SETTLEMENT_STATUS_OBJECT[MENTORING_TRANSACTION_STATUS.CANCELED],
    value: MENTORING_TRANSACTION_STATUS.CANCELED,
  },
]

export const ORDER_STATUS_OBJECT: Record<string, string> = {
  [ORDER_STATUS.PENDING]: '대기',
  [ORDER_STATUS.COMPLETED]: '완료',
  [ORDER_STATUS.CANCELED]: '취소',
}

export const ORDER_STATUS_ARRAY = [
  {
    label: '전체',
    value: 'COMPLETE,CANCELED',
  },
  {
    label: SETTLEMENT_STATUS_OBJECT[MENTORING_TRANSACTION_STATUS.PENDING],
    value: MENTORING_TRANSACTION_STATUS.PENDING,
  },
  {
    label: SETTLEMENT_STATUS_OBJECT[MENTORING_TRANSACTION_STATUS.COMPLETE],
    value: MENTORING_TRANSACTION_STATUS.COMPLETE,
  },
  {
    label: SETTLEMENT_STATUS_OBJECT[MENTORING_TRANSACTION_STATUS.CANCELED],
    value: MENTORING_TRANSACTION_STATUS.CANCELED,
  },
]
